MailBots:
  - Name: "My LLM Chatbot"
    Send:
      SMTP:
        Username: chatbot@example.com
        Password: your-password
        Server: smtp.example.com
        Port: 465
        Encryption: SSL/TLS
        # Port: 587
        # Encryption: STARTTLS
        # Port: 25
        # Encryption: NONE
    Receive:
      Mode: MarkRead
      # Mode: Delete
      Interval: 60
      IMAP:
        Username: chatbot@example.com
        Password: your-password
        Server: imap.example.com
        Port: 993
        Encryption: SSL/TLS
        # Port: 143
        # Encryption: STARTTLS
        # Port: 143
        # Encryption: NONE
      Queue:
        # Default based on Workers.Type
        # Type: Thread
        # Type: Process
        Parameters:
          maxsize: 100
      Workers:
        Type: Thread
        # Type: Process
        Count: 4
    Security:
      Mode: AllowList
      Addresses:
        - "me@example.com"
