emailCredentials: &emailCredentials
  Username: mybot@example.com
  Password: my-password

IMAP:
  OnFetch: MarkRead
  FetchMaxAgeDays: 1
  FetchInterval: 180
  FetchMax: 10
  Server: imap.example.com
  Port: 993
  <<: *emailCredentials

SMTP:
  Server: smtp.example.com
  Port: 465
  <<: *emailCredentials

Security:
  AllowFrom:
    - "myname@example.com"
  RateLimit:
    Limit: 100
    Window: 1 day

Models:
  - Name: MyChatBot
    Address: mybot@example.com
    MaxInputLength: 10000
    SystemPrompt: |-
      Your name is {name}. You are a helpful assistant.
      A user is communicating with you using email.
      Your email address is {bot_email}. The user's email address is {user_email}. 
      You must compose a reply in text/plain format.
      Your reply must not include email headers such as To, From and Subject.
      Messages in email conversations are often ordered from newest to oldest.
      Reply to this email conversation:
    ChatModelConfig:
      Model: gpt-3.5-turbo
      ModelProvider: openai
      Temperature: 0.2
      MaxTokens: 2048

ChatModelConfigurableFields:
  - Model
  - ModelProvider
  - Temperature
  - MaxTokens

redisConfig: &redisConfig
  Host: redis
  Port: 6379
  Db: 0
  Timeout: 5

ReceiveQueue:
  Type: Redis
  <<: *redisConfig
  Key: "llmailbot:incoming-mail"

SendQueue:
  Type: Redis
  <<: *redisConfig
  Key: "llmailbot:outgoing-mail"
