
services:
  # Base service definition (never started directly)
  llmailbot-base: &llmailbot-base
    profiles: ["never"]
    build: ../
    image: jbchouinard/llmailbot:slim
    volumes:
      - ./config.yaml:/app/config.yaml
    depends_on:
      - redis
  
  # Fetcher service - gets emails from IMAP
  fetcher:
    <<: *llmailbot-base
    profiles: []
    command: run fetch
  
  # Worker service - processes emails with LLM
  worker:
    <<: *llmailbot-base
    profiles: []
    command: run reply
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./requirements.txt:/app/requirements.txt
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      # Add other API keys as needed
  
  # Sender service - sends replies via SMTP
  sender:
    <<: *llmailbot-base
    profiles: []
    command: run send
  
  # Redis for message queuing
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data

volumes:
  redis-data:
